-- Create profiles table if not exists
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  name text,
  avatar text,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Add role column if it doesn't exist
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'role') then 
    alter table public.profiles add column role text default 'user'; 
  end if; 
end $$;

-- Policies for Profiles
drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

drop policy if exists "Users can insert their own profile." on public.profiles;
create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on public.profiles;
create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Venues Table
create table if not exists public.venues (
  id bigint generated by default as identity primary key,
  name text not null,
  type text,
  sport text,
  location text,
  rating numeric default 0,
  price text,
  image text,
  amenities text[],
  coordinates numeric[],
  gallery text[],
  description text,
  owner_id uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Venues
alter table public.venues enable row level security;

-- Policies for Venues
drop policy if exists "Venues are viewable by everyone." on public.venues;
create policy "Venues are viewable by everyone."
  on public.venues for select
  using ( true );

drop policy if exists "Authenticated users can insert venues." on public.venues;
create policy "Authenticated users can insert venues."
  on public.venues for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Owners and Admins can update venues." on public.venues;
create policy "Owners and Admins can update venues."
  on public.venues for update
  using ( 
    auth.uid() = owner_id or 
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Owners and Admins can delete venues." on public.venues;
create policy "Owners and Admins can delete venues."
  on public.venues for delete
  using ( 
    auth.uid() = owner_id or 
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- Claim Requests Table
create table if not exists public.claim_requests (
  id bigint generated by default as identity primary key,
  venue_id bigint references public.venues(id),
  requester_id uuid references public.profiles(id),
  business_name text,
  contact_email text,
  contact_phone text,
  status text default 'pending', -- pending, approved, rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Claims
alter table public.claim_requests enable row level security;

-- Policies for Claims
drop policy if exists "Users can see their own claims." on public.claim_requests;
create policy "Users can see their own claims."
  on public.claim_requests for select
  using ( auth.uid() = requester_id );

drop policy if exists "Users can create claims." on public.claim_requests;
create policy "Users can create claims."
  on public.claim_requests for insert
  with check ( auth.uid() = requester_id );

-- User Venue Interactions
create table if not exists public.user_venue_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  venue_id bigint references public.venues(id),
  interaction_type text, -- 'page_view', 'booking', 'play_intent', 'image_upload'
  interaction_data jsonb, -- e.g. { date: '2023-10-27' }
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.user_venue_interactions enable row level security;

drop policy if exists "Users can insert interactions." on public.user_venue_interactions;
create policy "Users can insert interactions."
  on public.user_venue_interactions for insert
  with check ( auth.uid() = user_id );

drop policy if exists "Everyone can view interactions" on public.user_venue_interactions;
create policy "Everyone can view interactions"
  on public.user_venue_interactions for select
  using ( true );


-- Trigger for Profile Creation (Ensure it exists)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role, avatar)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'name', 
    coalesce(new.raw_user_meta_data->>'role', 'user'),
    coalesce(new.raw_user_meta_data->>'avatar', 'https://ui-avatars.com/api/?name=' || (new.raw_user_meta_data->>'name'))
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger definition (conditional drop to avoid error if exists, or idempotent create)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


