export const venues = [
  {
    id: 1,
    name: "Thunderdome Arena",
    type: "Stadium",
    sport: "Basketball",
    location: "Downtown",
    rating: 4.8,
    price: "$50/hr",
    image: "/venues/Thunderdome Arena.jpg",
    amenities: ["Lighting", "Seating", "Locker Rooms"],
    coordinates: [40.7128, -74.0060]
  },
  {
    id: 2,
    name: "Iron Pump Gym",
    type: "Gym",
    sport: "Fitness",
    location: "Westside",
    rating: 4.5,
    price: "$15/day",
    image: "/venues/Iron Pump Gym.jpg",
    amenities: ["Weights", "Cardio", "Sauna"],
    coordinates: [40.7300, -74.0200]
  },
  {
    id: 3,
    name: "Greenfield Soccer Park",
    type: "Field",
    sport: "Soccer",
    location: "North Hills",
    rating: 4.9,
    price: "$80/match",
    image: "/venues/Greenfield Soccer Park.jpg",
    amenities: ["Grass", "Parking", "Showers"],
    coordinates: [40.7500, -73.9800]
  },
  {
    id: 4,
    name: "Sky Court Tennis",
    type: "Court",
    sport: "Tennis",
    location: "Skyline Heights",
    rating: 4.7,
    price: "$30/hr",
    image: "/venues/Sky Court Tennis.jpg",
    amenities: ["Hard Court", "Equipment Rental"],
    coordinates: [40.7600, -73.9500]
  },
  {
    id: 5,
    name: "City Hoop Park",
    type: "Public Court",
    sport: "Basketball",
    location: "Urban District",
    rating: 4.2,
    price: "Free",
    image: "/venues/City Hoop Park.jpg",
    amenities: ["Open Access", "Water Fountain"],
    coordinates: [40.7200, -73.9900]
  },
  {
    id: 6,
    name: "Riverside Volleyball Sand",
    type: "Public Field",
    sport: "Volleyball",
    location: "River Bank",
    rating: 4.6,
    price: "Free",
    image: "/venues/Riverside Volleyball Sand.jpg",
    amenities: ["Sand Court", "Picnic Area"],
    coordinates: [40.7050, -74.0150]
  },
  {
    id: 7,
    name: "Grand Slam Batting Cages",
    type: "Cage",
    sport: "Baseball",
    location: "Eastside",
    rating: 4.4,
    price: "$20/hr",
    image: "/venues/Grand Slam Batting Cages.jpg",
    amenities: ["Machine Pitch", "Gear Rental"],
    coordinates: [40.7400, -73.9200]
  },
  {
    id: 8,
    name: "AquaCenter Pool",
    type: "Pool",
    sport: "Swimming",
    location: "Midtown",
    rating: 4.9,
    price: "$10/visit",
    image: "/venues/AquaCenter Pool.jpg",
    amenities: ["Olympic Size", "Heated", "Lockers"],
    coordinates: [40.7550, -73.9950]
  },
  // New Generic Public Places
  {
    id: 9,
    name: "Maplewood Community Park",
    type: "Public Park",
    sport: "Multi-sport",
    location: "Maplewood",
    rating: 4.3,
    price: "Free",
    image: "/venues/Maplewood Community Park.jpg",
    amenities: ["Jogging Track", "Open Field"],
    coordinates: [40.7800, -73.9600]
  },
  {
    id: 10,
    name: "Sunset Street Courts",
    type: "Public Court",
    sport: "Basketball",
    location: "Sunset Bvld",
    rating: 4.1,
    price: "Free",
    image: "/venues/Sunset Street Courts.jpg",
    amenities: ["Concrete Court", "Night Lights"],
    coordinates: [40.6900, -73.9400]
  },
  {
    id: 11,
    name: "Lakeside Run Trail",
    type: "Public Park",
    sport: "Running",
    location: "Lakeside",
    rating: 4.8,
    price: "Free",
    image: "/venues/Lakeside Run Trail.jpg",
    amenities: ["Scenic View", "Trail"],
    coordinates: [40.7700, -73.9700]
  },
  {
    id: 12,
    name: "Veteran's Memorial Field",
    type: "Public Field",
    sport: "Soccer",
    location: "Old Town",
    rating: 4.0,
    price: "Free",
    image: "/venues/Veteran's Memorial Field.jpg",
    amenities: ["Grass Field", "Seating"],
    coordinates: [40.7100, -74.0500]
  },
  {
    id: 13,
    name: "Eastside Skate Park",
    type: "Public Park",
    sport: "Skating",
    location: "Eastside",
    rating: 4.7,
    price: "Free",
    image: "/venues/Eastside Skate Park.jpg",
    amenities: ["Ramps", "Rails"],
    coordinates: [40.7300, -73.9000]
  }
];
