export const venues = [
  {
    id: 1,
    name: "Thunderdome Arena",
    type: "Stadium",
    sport: "Basketball",
    location: "Downtown",
    rating: 4.8,
    price: "$50/hr",
    imageGradient: "linear-gradient(45deg, #FF512F, #DD2476)",
    amenities: ["Lighting", "Seating", "Locker Rooms"],
    coordinates: [40.7128, -74.0060]
  },
  {
    id: 2,
    name: "Iron Pump Gym",
    type: "Gym",
    sport: "Fitness",
    location: "Westside",
    rating: 4.5,
    price: "$15/day",
    imageGradient: "linear-gradient(45deg, #4776E6, #8E54E9)",
    amenities: ["Weights", "Cardio", "Sauna"],
    coordinates: [40.7300, -74.0200]
  },
  {
    id: 3,
    name: "Greenfield Soccer Park",
    type: "Field",
    sport: "Soccer",
    location: "North Hills",
    rating: 4.9,
    price: "$80/match",
    imageGradient: "linear-gradient(45deg, #11998e, #38ef7d)",
    amenities: ["Grass", "Parking", "Showers"],
    coordinates: [40.7500, -73.9800]
  },
  {
    id: 4,
    name: "Sky Court Tennis",
    type: "Court",
    sport: "Tennis",
    location: "Skyline Heights",
    rating: 4.7,
    price: "$30/hr",
    imageGradient: "linear-gradient(45deg, #f2994a, #f2c94c)",
    amenities: ["Hard Court", "Equipment Rental"],
    coordinates: [40.7600, -73.9500]
  },
  {
    id: 5,
    name: "City Hoop Park",
    type: "Public Court",
    sport: "Basketball",
    location: "Urban District",
    rating: 4.2,
    price: "Free",
    imageGradient: "linear-gradient(45deg, #FF416C, #FF4B2B)",
    amenities: ["Open Access", "Water Fountain"],
    coordinates: [40.7200, -73.9900]
  },
  {
    id: 6,
    name: "Riverside Volleyball Sand",
    type: "Public Field",
    sport: "Volleyball",
    location: "River Bank",
    rating: 4.6,
    price: "Free",
    imageGradient: "linear-gradient(45deg, #FDC830, #F37335)",
    amenities: ["Sand Court", "Picnic Area"],
    coordinates: [40.7050, -74.0150]
  },
  {
    id: 7,
    name: "Grand Slam Batting Cages",
    type: "Cage",
    sport: "Baseball",
    location: "Eastside",
    rating: 4.4,
    price: "$20/hr",
    imageGradient: "linear-gradient(45deg, #3a1c71, #d76d77, #ffaf7b)",
    amenities: ["Machine Pitch", "Gear Rental"],
    coordinates: [40.7400, -73.9200]
  },
  {
    id: 8,
    name: "AquaCenter Pool",
    type: "Pool",
    sport: "Swimming",
    location: "Midtown",
    rating: 4.9,
    price: "$10/visit",
    imageGradient: "linear-gradient(45deg, #00c6ff, #0072ff)",
    amenities: ["Olympic Size", "Heated", "Lockers"],
    coordinates: [40.7550, -73.9950]
  },
  // New Generic Public Places
  {
    id: 9,
    name: "Maplewood Community Park",
    type: "Public Park",
    sport: "Multi-sport",
    location: "Maplewood",
    rating: 4.3,
    price: "Free",
    imageGradient: "linear-gradient(45deg, #56ab2f, #a8e063)",
    amenities: ["Jogging Track", "Open Field"],
    coordinates: [0, 0] // Placeholder
  },
  {
    id: 10,
    name: "Sunset Street Courts",
    type: "Public Court",
    sport: "Basketball",
    location: "Sunset Bvld",
    rating: 4.1,
    price: "Free",
    imageGradient: "linear-gradient(45deg, #cb2d3e, #ef473a)",
    amenities: ["Concrete Court", "Night Lights"],
    coordinates: [0, 0]
  },
  {
    id: 11,
    name: "Lakeside Run Trail",
    type: "Public Park",
    sport: "Running",
    location: "Lakeside",
    rating: 4.8,
    price: "Free",
    imageGradient: "linear-gradient(45deg, #1fa2ff, #12d8fa, #a6ffcb)",
    amenities: ["Scenic View", "Trail"],
    coordinates: [0, 0]
  },
  {
    id: 12,
    name: "Veteran's Memorial Field",
    type: "Public Field",
    sport: "Soccer",
    location: "Old Town",
    rating: 4.0,
    price: "Free",
    imageGradient: "linear-gradient(45deg, #add100, #7b920a)",
    amenities: ["Grass Field", "Seating"],
    coordinates: [0, 0]
  },
  {
    id: 13,
    name: "Eastside Skate Park",
    type: "Public Park",
    sport: "Skating",
    location: "Eastside",
    rating: 4.7,
    price: "Free",
    imageGradient: "linear-gradient(45deg, #232526, #414345)",
    amenities: ["Ramps", "Rails"],
    coordinates: [0, 0]
  }
];
